config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :properties
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'properties#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    has_one_attached :image
    has_many :reservations, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    before_save :calculate_total_price 
    def calculate_total_price
       self.total = Property.find_by(id: property_id).pricexnight*numbernights*numberguests
    end    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties, dependent: :destroy      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:title, :description, :pricexnight)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @property = Property.find_by(id:params[:format])
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      @property = Property.find_by(id:params[:format])
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      @property = Property.find_by(id:params[:format])
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:name, :lastname, :email, :phone, :numbernights, :numberguests, :approved, :property_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :pricexnight %>
    <%= form.text_field :pricexnight, class:"form-control" %>
  </div>
  <div class="field form-group">
    <% if property.image.attached? %>
        <%= image_tag property.image, style: "width:200px; display: block" %>
    <% end %>
        <%= form.label :image %>
        <%= form.file_field :images, multiple: true, class:"form-control" %>
  </div>
  <br>
  <div class="actions form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="nav justify-content-end">
  <% if user_signed_in? %>
      <a class="nav-link active" href="/users/edit">User</a>
      <a class="nav-link active" href="reservations#show">Reservations</a>
      <a class="nav-link active" href="/users/sign_out">Sign out</a>
  <%else%>  
      <a class="nav-link active" href="/users/sign_in">Sign in</a>  
  <%end%>
</nav>
<h3>Properties</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Price per night</th>
      <th scope="col">Photos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= property.description %></td>
        <td><%= property.pricexnight %></td>
        <td><%= property.image %></td>
        <td class="btn btn-link"><%= link_to 'Show', property %></td>
        <% if user_signed_in? %>
          <td class="btn btn-link"><%= link_to 'Edit', edit_property_path(property) %></td>
          <td class="btn btn-link"><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <td class="btn btn-link"><%= link_to 'New Reservation', new_reservation_path(property.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
<br>
<button type="button" class="btn btn-dark btn-md justify-content-end"><%= link_to 'New Property', new_property_path %></button>
<%end%>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @property.pricexnight %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @property.image %>
</p>

</table>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="field form-row">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-row">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, class:"form-control" %>
  </div>

  <div class="field form-row">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-row">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field form-row">
    <%= form.label :numbernights %>
    <%= form.text_field :numbernights, class:"form-control" %>
  </div>

  <div class="field form-row">
    <%= form.label :numberguests %>
    <%= form.text_field :numberguests, class:"form-control"  %>
  </div>

  <div>
    <%= form.hidden_field :property_id, value: property.id %>
  </div>

  <div>
    <%= form.hidden_field :property_value, value: property.pricexnight %>
    <%= form.label :total %>
    <%= form.text_field :total , disabled: true,  class:"form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit  class:"btn btn-primary" %>
  </div>

</form>  
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="nav justify-content-end">
  <a class="nav-link active" href="/users">Users</a>
  <a class="nav-link active" href="/reservations">Reservations</a>
  <a class="nav-link active" href="/properties">Properties</a>
  <a class="nav-link active" href="/users/sign_out">Sign out</a>
</nav>

<h3>Reservations</h3>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Number of nights</th>
      <th scope="col" >Number of guests</th>
      <th scope="col" class="hide">Approved</th>
      <th scope="col" >Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.lastname %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.phone %></td>
        <td><%= reservation.numbernights %></td>
        <td><%= reservation.numberguests %></td>
        <td><%= reservation.approved %></td>
        <td><%= reservation.total %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reservations/new.html.erb
<h3>New Reservation</h3>

<%= render 'form', reservation: @reservation, property: @property %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @reservation.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reservation.phone %>
</p>

<p>
  <strong>Number of nights:</strong>
  <%= @reservation.numbernights %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @reservation.numberguests %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @reservation.approved %>
</p>

<%= link_to 'Back', reservations_path %>